export const ACTION_TYPE = {
    SAVE_CATEGORIA : "SAVE_CATEGORIA",
    SAVE_CATEGORIA_SUCCESS : "SAVE_CATEGORIA_SUCCESS",
    SAVE_CATEGORIA_ERROR : "SAVE_CATEGORIA_ERROR",

    UPDATE_CATEGORIA : "UPDATE_CATEGORIA",
    UPDATE_CATEGORIA_SUCCESS : "UPDATE_CATEGORIA_SUCCESS",
    UPDATE_CATEGORIA_ERROR : "UPDATE_CATEGORIA_ERROR",

    DELETE_CATEGORIA : "DELETE_CATEGORIA",
    DELETE_CATEGORIA_SUCCESS : "DELETE_CATEGORIA_SUCCESS",
    DELETE_CATEGORIA_ERROR : "DELETE_CATEGORIA_ERROR",

    LIST_CATEGORIA : "LIST_CATEGORIA",
    LIST_CATEGORIA_SUCCESS : "LIST_CATEGORIA_SUCCESS",
    LIST_CATEGORIA_ERROR : "LIST_CATEGORIA_ERROR",
}